//! Generating a C header of event ids from capture metadata.
//!
//! There are two places an event id is written down: the firmware that sends it, and the
//! metadata file that names it. When those drift, a capture reports `0x0104` where it used to
//! say `BLE_TX`, or worse, reports `BLE_TX` for something else entirely — and nothing fails,
//! because an event id is opaque by design and neither side can tell.
//!
//! Generating one from the other removes the drift rather than documenting it. The metadata
//! file wins because it is the one a person edits and the one that ends up inside the capture.
//!
//! ```no_run
//! use wattson_core::codegen::{HeaderOptions, c_header};
//! use wattson_core::metadata::CaptureMetadata;
//!
//! let meta = CaptureMetadata::from_toml_file("events.toml".as_ref())?;
//! let header = c_header(&meta, &HeaderOptions::default())?;
//! std::fs::write("pp_events.h", header)?;
//! # Ok::<(), Box<dyn std::error::Error>>(())
//! ```
//!
//! This lives in `core` rather than the CLI so a build script, the CLI, and a future desktop
//! app all emit identical headers.

use std::fmt::Write as _;

use crate::error::CaptureError;
use crate::metadata::CaptureMetadata;

/// How to shape the generated header.
#[derive(Debug, Clone)]
pub struct HeaderOptions {
    /// Prefix on every generated macro. `PP_EVT_` gives `PP_EVT_BLE_TX`.
    pub prefix: String,
    /// Include guard. Derived from the file name when generated by the CLI.
    pub include_guard: String,
    /// Source description for the generated banner — a path, usually.
    pub source: String,
}

impl Default for HeaderOptions {
    fn default() -> Self {
        HeaderOptions {
            prefix: "PP_EVT_".to_string(),
            include_guard: "PP_EVENTS_H".to_string(),
            source: "capture metadata".to_string(),
        }
    }
}

/// Render `name` as a C macro identifier suffix.
///
/// Anything that is not alphanumeric becomes an underscore, which is what a C identifier
/// allows. Runs are not collapsed and a leading digit is not stripped: both would silently map
/// two distinct event names onto one macro, and the collision check below would then have to
/// explain a mangling nobody asked for. A name that produces an invalid identifier is
/// reported, not repaired.
pub fn c_identifier(name: &str) -> String {
    name.chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect::<String>()
        .to_ascii_uppercase()
}

/// Generate a C header defining every event id in `meta`.
///
/// Fails when two event names collapse onto one macro, or when a name cannot be a C
/// identifier at all. Both would produce a header that compiles into the wrong ids.
pub fn c_header(meta: &CaptureMetadata, opts: &HeaderOptions) -> Result<String, CaptureError> {
    meta.validate()?;

    let mut seen: Vec<(String, &str)> = Vec::new();
    for event in &meta.events {
        let ident = c_identifier(&event.name);
        if ident.starts_with(|c: char| c.is_ascii_digit()) {
            return Err(CaptureError::Metadata(format!(
                "event name {:?} starts with a digit, so it cannot become a C macro; \
                 rename it or set a name that starts with a letter",
                event.name
            )));
        }
        if let Some((_, other)) = seen.iter().find(|(i, _)| *i == ident) {
            return Err(CaptureError::Metadata(format!(
                "event names {:?} and {:?} both become {}{}; rename one",
                other, event.name, opts.prefix, ident
            )));
        }
        seen.push((ident, &event.name));
    }

    let mut out = String::new();
    let guard = &opts.include_guard;

    writeln!(out, "/*").expect("string write");
    writeln!(out, " * Event ids for wattson instrumentation.").expect("string write");
    writeln!(out, " *").expect("string write");
    writeln!(
        out,
        " * GENERATED FROM {} - do not edit. Regenerate with:",
        opts.source
    )
    .expect("string write");
    writeln!(out, " *").expect("string write");
    writeln!(
        out,
        " *     wattson gen-header {} -o <this file>",
        opts.source
    )
    .expect("string write");
    writeln!(out, " *").expect("string write");
    writeln!(
        out,
        " * Editing an id here without editing the metadata makes the capture name the wrong"
    )
    .expect("string write");
    writeln!(
        out,
        " * event, and nothing will fail: an event id is opaque on the wire, so neither the"
    )
    .expect("string write");
    writeln!(out, " * firmware nor the host can tell.").expect("string write");
    writeln!(out, " */").expect("string write");
    writeln!(out).expect("string write");
    writeln!(out, "#ifndef {guard}").expect("string write");
    writeln!(out, "#define {guard}").expect("string write");
    writeln!(out).expect("string write");

    if meta.events.is_empty() {
        writeln!(out, "/* The metadata declares no events. */").expect("string write");
    }

    for event in &meta.events {
        let ident = c_identifier(&event.name);
        let prefix = &opts.prefix;

        writeln!(out, "/* {}", event.name).expect("string write");
        if let Some(category) = &event.category {
            writeln!(out, " * category: {category}").expect("string write");
        }
        if let Some(units) = &event.value_units {
            writeln!(out, " * value: {units}").expect("string write");
        }
        if event.latency_compensation_ns != 0 {
            writeln!(
                out,
                " * latency compensation: {} ns, applied by the host",
                event.latency_compensation_ns
            )
            .expect("string write");
        }
        match event.stop_id {
            None => writeln!(
                out,
                " * point event: a time, but no duration and no energy */"
            )
            .expect("string write"),
            Some(_) => writeln!(out, " */").expect("string write"),
        }

        writeln!(out, "#define {prefix}{ident} 0x{:04X}u", event.start_id).expect("string write");

        if let Some(stop) = event.stop_id {
            writeln!(out, "#define {prefix}{ident}_STOP 0x{stop:04X}u").expect("string write");
            if stop == event.start_id.wrapping_add(1) {
                // The convention PP_SCOPE relies on, so say when it holds. A reader who does
                // not know whether it does will reach for PP_SCOPE_ID every time.
                writeln!(
                    out,
                    "/* stop = start + 1, so PP_SCOPE({prefix}{ident}) works. */"
                )
                .expect("string write");
            } else {
                writeln!(
                    out,
                    "/* stop is not start + 1: use PP_SCOPE_ID({prefix}{ident}, \
                     {prefix}{ident}_STOP). */"
                )
                .expect("string write");
            }
        }
        writeln!(out).expect("string write");
    }

    writeln!(out, "#endif /* {guard} */").expect("string write");
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::metadata::EventDef;

    fn meta(events: Vec<EventDef>) -> CaptureMetadata {
        CaptureMetadata {
            events,
            ..Default::default()
        }
    }

    #[test]
    fn a_scope_event_gets_both_ids() {
        let m = meta(vec![EventDef::scope("BLE_TX", 0x0100, 0x0101)]);
        let h = c_header(&m, &HeaderOptions::default()).expect("generate");

        assert!(h.contains("#define PP_EVT_BLE_TX 0x0100u"));
        assert!(h.contains("#define PP_EVT_BLE_TX_STOP 0x0101u"));
        assert!(
            h.contains("PP_SCOPE(PP_EVT_BLE_TX) works"),
            "0x0101 is 0x0100 + 1"
        );
    }

    #[test]
    fn a_pair_that_breaks_the_convention_says_so() {
        let m = meta(vec![EventDef::scope("APART", 0x1000, 0x2000)]);
        let h = c_header(&m, &HeaderOptions::default()).expect("generate");

        assert!(h.contains("PP_SCOPE_ID(PP_EVT_APART, PP_EVT_APART_STOP)"));
        assert!(!h.contains("PP_SCOPE(PP_EVT_APART) works"));
    }

    #[test]
    fn a_point_event_gets_one_id_and_is_labelled() {
        let m = meta(vec![EventDef::point("PACKET_TX", 0x0110)]);
        let h = c_header(&m, &HeaderOptions::default()).expect("generate");

        assert!(h.contains("#define PP_EVT_PACKET_TX 0x0110u"));
        assert!(!h.contains("PP_EVT_PACKET_TX_STOP"));
        assert!(h.contains("point event"));
    }

    #[test]
    fn names_become_valid_identifiers() {
        assert_eq!(c_identifier("BLE TX"), "BLE_TX");
        assert_eq!(c_identifier("radio.tx"), "RADIO_TX");
        assert_eq!(c_identifier("i2c-read"), "I2C_READ");
    }

    /// Two names that mangle to the same macro must fail, not silently define one twice.
    #[test]
    fn colliding_identifiers_are_refused() {
        let m = meta(vec![
            EventDef::point("radio tx", 0x0100),
            EventDef::point("radio.tx", 0x0200),
        ]);
        let err = c_header(&m, &HeaderOptions::default()).expect_err("must collide");
        assert!(
            err.to_string().contains("PP_EVT_RADIO_TX"),
            "the error names the collision: {err}"
        );
    }

    #[test]
    fn a_name_that_cannot_be_an_identifier_is_refused() {
        let m = meta(vec![EventDef::point("2fast", 0x0100)]);
        let err = c_header(&m, &HeaderOptions::default()).expect_err("must refuse");
        assert!(err.to_string().contains("starts with a digit"), "{err}");
    }

    /// Metadata that would not survive analysis must not survive code generation either.
    #[test]
    fn invalid_metadata_is_refused_before_anything_is_written() {
        let m = meta(vec![
            EventDef::point("A", 0x0100),
            EventDef::point("B", 0x0100),
        ]);
        assert!(c_header(&m, &HeaderOptions::default()).is_err());
    }

    #[test]
    fn the_header_is_guarded_and_self_describing() {
        let m = meta(vec![EventDef::scope("BLE_TX", 0x0100, 0x0101)]);
        let opts = HeaderOptions {
            include_guard: "MY_EVENTS_H".to_string(),
            source: "events.toml".to_string(),
            ..Default::default()
        };
        let h = c_header(&m, &opts).expect("generate");

        assert!(h.contains("#ifndef MY_EVENTS_H"));
        assert!(h.contains("#define MY_EVENTS_H"));
        assert!(h.trim_end().ends_with("#endif /* MY_EVENTS_H */"));
        assert!(h.contains("GENERATED FROM events.toml"));
    }

    #[test]
    fn empty_metadata_still_produces_a_valid_header() {
        let h = c_header(&meta(vec![]), &HeaderOptions::default()).expect("generate");
        assert!(h.contains("declares no events"));
        assert!(h.contains("#endif"));
    }
}
